version: "3.3"

services:

  # backend
  damap-be:
    image: ghcr.io/sharedrdm/damap-backend-mug:${DAMAP_BE_VERSION}
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - fits-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/live"]
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
      - "8080:8080"
    environment:
      DAMAP_ENV: ${DAMAP_ENV}
      DAMAP_ORIGINS: ${DAMAP_ORIGINS}
      DAMAP_AUTH_BACKEND_URL: ${DAMAP_AUTH_BACKEND_URL}
      DAMAP_AUTH_BACKEND_CLIENT: ${DAMAP_AUTH_BACKEND_CLIENT}
      DAMAP_AUTH_FRONTEND_URL: ${DAMAP_AUTH_FRONTEND_URL}
      DAMAP_AUTH_FRONTEND_CLIENT: ${DAMAP_AUTH_FRONTEND_CLIENT}
      DAMAP_AUTH_SCOPE: ${DAMAP_AUTH_SCOPE}
      DAMAP_AUTH_USER: ${DAMAP_AUTH_USER}
      DAMAP_DATASOURCE_URL: ${DAMAP_DATASOURCE_URL}
      DAMAP_DATASOURCE_USERNAME: ${DAMAP_DATASOURCE_USERNAME}
      DAMAP_DATASOURCE_PASSWORD: ${DAMAP_DATASOURCE_PASSWORD}
      DAMAP_PROJECTS_URL: ${DAMAP_PROJECTS_URL}
      DAMAP_PERSONS_URL: ${DAMAP_PERSONS_URL}
      DAMAP_FITS_URL: ${DAMAP_FITS_URL}
      DAMAP_GOTENBERG_URL: ${DAMAP_GOTENBERG_URL}
      DAMAP_MUG_API_AUTH_TOKEN: ${DAMAP_MUG_API_AUTH_TOKEN}
      DAMAP_TITLE: "Med Uni Graz DAMAP Tool"

  # frontend
  damap-fe:
    image: ghcr.io/sharedrdm/damap-frontend-mug:${DAMAP_FE_VERSION}
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - damap-be
    ports:
      - "8000:8000"

  # fits service
  fits-service:
    image: islandora/fits:main
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8089:8081"

  # Gotenberg Service for live preview
  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
